In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

In [2]:
df = pd.read_csv('/Users/zeerakkhan/Downloads/heart.csv')

In [3]:
df.head()

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease
0,40,M,ATA,140,289,0,Normal,172,N,0.0,Up,0
1,49,F,NAP,160,180,0,Normal,156,N,1.0,Flat,1
2,37,M,ATA,130,283,0,ST,98,N,0.0,Up,0
3,48,F,ASY,138,214,0,Normal,108,Y,1.5,Flat,1
4,54,M,NAP,150,195,0,Normal,122,N,0.0,Up,0

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 918 entries, 0 to 917
Data columns (total 12 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Age             918 non-null    int64
 1   Sex             918 non-null    object
 2   ChestPainType   918 non-null    object
 3   RestingBP       918 non-null    int64
 4   Cholesterol     918 non-null    int64
 5   FastingBS       918 non-null    int64
 6   RestingECG      918 non-null    object
 7   MaxHR           918 non-null    int64
 8   ExerciseAngina  918 non-null    object
 9   Oldpeak         918 non-null    float64
 10  ST_Slope        918 non-null    object
 11  HeartDisease    918 non-null    int64
dtypes: float64(1), int64(6), object(5)
memory usage: 86.2+ KB

## Data Preprocessing and Cleaning

In [6]:
df

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease
0,40,M,ATA,140,289,0,Normal,172,N,0.0,Up,0
1,49,F,NAP,160,180,0,Normal,156,N,1.0,Flat,1
2,37,M,ATA,130,283,0,ST,98,N,0.0,Up,0
3,48,F,ASY,138,214,0,Normal,108,Y,1.5,Flat,1
4,54,M,NAP,150,195,0,Normal,122,N,0.0,Up,0
...,...,...,...,...,...,...,...,...,...,...,...,...
913,45,M,TA,110,264,0,Normal,132,N,1.2,Flat,1
914,68,M,ASY,144,193,1,Normal,141,N,3.4,Flat,1
915,57,M,ASY,130,131,0,Normal,115,Y,1.2,Flat,1
916,57,F,ATA,130,236,0,LVH,174,N,0.0,Flat,1
917,38,M,NAP,138,175,0,Normal,173,N,0.0,Up,0

In [7]:
df_encoded = pd.get_dummies(df,drop_first= True)

In [8]:
df_encoded

,Age,RestingBP,Cholesterol,FastingBS,MaxHR,Oldpeak,HeartDisease,Sex_M,ChestPainType_ATA,ChestPainType_NAP,ChestPainType_TA,RestingECG_Normal,RestingECG_ST,ExerciseAngina_Y,ST_Slope_Flat,ST_Slope_Up
0,40,140,289,0,172,0.0,0,True,True,False,False,True,False,False,False,True
1,49,160,180,0,156,1.0,1,False,False,True,False,True,False,False,True,False
2,37,130,283,0,98,0.0,0,True,True,False,False,False,True,False,False,True
3,48,138,214,0,108,1.5,1,False,False,False,False,True,False,True,True,False
4,54,150,195,0,122,0.0,0,True,False,True,False,True,False,False,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
913,45,110,264,0,132,1.2,1,True,False,False,True,True,False,False,True,False
914,68,144,193,1,141,3.4,1,True,False,False,False,True,False,False,True,False
915,57,130,131,0,115,1.2,1,True,False,False,False,True,False,True,True,False
916,57,130,236,0,174,0.0,1,False,True,False,False,False,False,False,True,False
917,38,138,175,0,173,0.0,0,True,False,True,False,True,False,False,False,True

In [9]:
df_encoded = df_encoded.astype(int)

In [10]:
df.columns

Index(['Age', 'Sex', 'ChestPainType', 'RestingBP', 'Cholesterol', 'FastingBS',
       'RestingECG', 'MaxHR', 'ExerciseAngina', 'Oldpeak', 'ST_Slope',
       'HeartDisease'],
      dtype='object')

In [11]:
X = df_encoded.drop('HeartDisease', axis = 1)
y = df_encoded['HeartDisease']

In [12]:
X

,Age,RestingBP,Cholesterol,FastingBS,MaxHR,Oldpeak,Sex_M,ChestPainType_ATA,ChestPainType_NAP,ChestPainType_TA,RestingECG_Normal,RestingECG_ST,ExerciseAngina_Y,ST_Slope_Flat,ST_Slope_Up
0,40,140,289,0,172,0,1,1,0,0,1,0,0,0,1
1,49,160,180,0,156,1,0,0,1,0,1,0,0,1,0
2,37,130,283,0,98,0,1,1,0,0,0,1,0,0,1
3,48,138,214,0,108,1,0,0,0,0,1,0,1,1,0
4,54,150,195,0,122,0,1,0,1,0,1,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
913,45,110,264,0,132,1,1,0,0,1,1,0,0,1,0
914,68,144,193,1,141,3,1,0,0,0,1,0,0,1,0
915,57,130,131,0,115,1,1,0,0,0,1,0,1,1,0
916,57,130,236,0,174,0,0,1,0,0,0,0,0,1,0
917,38,138,175,0,173,0,1,0,1,0,1,0,0,0,1

In [13]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing   import StandardScaler 
from sklearn.metrics import accuracy_score,f1_score,classification_report
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import GaussianNB
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier

In [14]:
X = df_encoded.drop('HeartDisease', axis = 1)
y = df_encoded['HeartDisease']

In [15]:
X_train, X_test, y_train, y_test = train_test_split(X, y, stratify=y, test_size=0.2, random_state=42)

In [16]:
scaler = StandardScaler()
X_trained = scaler.fit_transform(X_train)
X_tested = scaler.fit_transform(X_test)

In [17]:
models = {
        "Logistic Regression" : LogisticRegression(),
        "Naive Bayes" : GaussianNB(),
        "Decision Tree Classifier" : DecisionTreeClassifier(),
        "SVM(RBF Kernel)": SVC(),
        "KNN" : KNeighborsClassifier()   
}

In [18]:
result=[]

In [19]:
for name,model in models.items():
    model.fit(X_trained,y_train)
    y_pred = model.predict(X_tested)
    acc=accuracy_score(y_test,y_pred)
    f1= f1_score(y_test,y_pred)
    result.append(
        { 'model': name,
        'Accuracy': acc,
        'f1_score': f1}
    )

In [20]:
print(result)

[{'model': 'Logistic Regression', 'Accuracy': 0.8858695652173914, 'f1_score': 0.9004739336492891}, {'model': 'Naive Bayes', 'Accuracy': 0.9021739130434783, 'f1_score': 0.9117647058823529}, {'model': 'Decision Tree Classifier', 'Accuracy': 0.7336956521739131, 'f1_score': 0.7655502392344498}, {'model': 'SVM(RBF Kernel)', 'Accuracy': 0.8913043478260869, 'f1_score': 0.9047619047619048}, {'model': 'KNN', 'Accuracy': 0.875, 'f1_score': 0.8899521531100478}]

In [21]:
result

[{'model': 'Logistic Regression',
  'Accuracy': 0.8858695652173914,
  'f1_score': 0.9004739336492891},
 {'model': 'Naive Bayes',
  'Accuracy': 0.9021739130434783,
  'f1_score': 0.9117647058823529},
 {'model': 'Decision Tree Classifier',
  'Accuracy': 0.7336956521739131,
  'f1_score': 0.7655502392344498},
 {'model': 'SVM(RBF Kernel)',
  'Accuracy': 0.8913043478260869,
  'f1_score': 0.9047619047619048},
 {'model': 'KNN', 'Accuracy': 0.875, 'f1_score': 0.8899521531100478}]

## NOW saving this into pickle using joblib

In [23]:
import joblib 
joblib.dump(models['KNN'],'KNN_heart.pkl')
joblib.dump(scaler,'Scaler.pkl')
joblib.dump(X.columns.tolist(),'columns.pkl')

['columns.pkl']